import {Copy} from './site';
type Need={title:Copy;body:Copy;solutions:string[]};
export type Sector={slug:string;title:Copy;intro:Copy;image:string;needs:Need[];questions:Copy[]};
export const sectors:Sector[]=[
 {slug:'construction',title:{ar:'المقاولون الإنشائيون',en:'Construction contractors'},image:'industry-engineering-gnss',intro:{ar:'من تجهيز الموقع وتوقيع المحاور إلى مراجعة التنفيذ. اختر الحل حسب مرحلة مشروعك وطبيعة القياس، وجهّز فريقك بالمعدات والدعم المناسبين.',en:'From site preparation and setting out to construction verification. Match equipment and support to your project stage and measurement needs.'},needs:[
 {title:{ar:'توقيع المحاور والنقاط',en:'Setting out axes and points'},body:{ar:'لنقل المخططات إلى الموقع وتوقيع نقاط التنفيذ. ناقش التوتال ستيشن للأعمال التفصيلية، وGNSS للمواقع المفتوحة حسب الدقة والظروف المطلوبة.',en:'Transfer drawings to site and set out construction points. Consider total stations for detailed work and GNSS for open sites, based on required accuracy and conditions.'},solutions:['total-station','gnss']},
 {title:{ar:'التسوية والحفر',en:'Grading and excavation'},body:{ar:'لضبط المناسيب وتوجيه أعمال التربة. يبدأ الاختيار بنوع المعدة وموديلها وطبيعة العمل قبل تقييم توافق نظام التحكم.',en:'For level control and earthworks guidance. Start with machine type, model and task before assessing machine-control compatibility.'},solutions:['machine-control','total-station']},
 {title:{ar:'توثيق التنفيذ وتقدم الأعمال',en:'As-built and progress documentation'},body:{ar:'لتوثيق الوضع القائم ومقارنته بالمخططات. اختر المسح ثلاثي الأبعاد للتفاصيل، أو المسح الجوي لتغطية الموقع وفق المخرجات وترتيبات التشغيل.',en:'Capture site conditions for comparison with drawings. Consider 3D scanning for detail or aerial mapping for site coverage, according to deliverables and operating arrangements.'},solutions:['scanning','drone']},
 ],questions:[{ar:'ما مرحلة المشروع ومساحة الموقع؟',en:'What is the project stage and site area?'},{ar:'ما الدقة المطلوبة وطبيعة النقاط المراد توقيعها؟',en:'What accuracy and setting-out tasks are required?'},{ar:'هل المعدات مطلوبة لمدة مشروع أم للاستخدام المستمر؟',en:'Is equipment needed for one project or ongoing use?'}]},
 {slug:'surveying',title:{ar:'مكاتب المساحة',en:'Surveying offices'},image:'industry-surveying-total-station',intro:{ar:'جهّز مكتبك حسب الأعمال التي تنفذها يوميًا، من الرفع والتوقيع إلى التقاط الواقع وتسليم البيانات.',en:'Equip your office for its everyday work, from surveying and setting out to reality capture and data delivery.'},needs:[
 {title:{ar:'الرفع في المواقع المفتوحة',en:'Open-site surveying'},body:{ar:'اجمع الإحداثيات واربط أعمالك الميدانية بنظام المشروع. تقييم GNSS يبدأ بظروف استقبال الإشارة وطريقة التصحيح ومدى العمل.',en:'Collect coordinates within the project reference system. Assess GNSS using signal conditions, correction method and working range.'},solutions:['gnss']},
 {title:{ar:'القياسات التفصيلية والتوقيع',en:'Detailed measurement and setting out'},body:{ar:'للأعمال التي تحتاج رصدًا مباشرًا للنقاط وضبط الاتجاهات والمناسيب. حدد احتياجات المكتب من التوتال ستيشن والموازين والملحقات.',en:'For direct point observation, orientation and level control. Define your requirements for total stations, levels and accessories.'},solutions:['total-station']},
 {title:{ar:'توسيع خدمات التقاط الواقع',en:'Expanding reality-capture services'},body:{ar:'أضف مخرجات ثلاثية الأبعاد أو خرائط جوية حسب طلب عملائك، مع مناقشة المعالجة وصيغ التسليم وتدريب الفريق.',en:'Add 3D deliverables or aerial maps according to client needs, including processing, output formats and team training.'},solutions:['scanning','drone']}
 ],questions:[{ar:'ما أكثر نوع أعمال يتكرر في مكتبك؟',en:'Which tasks are most frequent in your office?'},{ar:'ما البرامج وصيغ التسليم المستخدمة؟',en:'Which software and delivery formats do you use?'},{ar:'كم فريقًا يعمل في الوقت نفسه؟',en:'How many teams operate simultaneously?'}]},
 {slug:'consulting',title:{ar:'الاستشارات الهندسية',en:'Engineering consultants'},image:'industry-construction-scanner',intro:{ar:'بيانات ميدانية أوضح لمراجعة المخططات وتوثيق الموجود والتحقق من التنفيذ. ابدأ بالمعلومة التي تحتاجها لاتخاذ القرار.',en:'Clearer field data for design review, existing-condition documentation and construction verification. Start with the information your decision requires.'},needs:[
 {title:{ar:'توثيق المباني والمنشآت',en:'Documenting buildings and structures'},body:{ar:'لالتقاط الواقع وإعداد بيانات ثلاثية الأبعاد تدعم المراجعة والتنسيق. حدد مستوى التفاصيل ومساحات العمل والمخرجات المطلوبة.',en:'Capture reality and prepare 3D data for review and coordination. Define detail levels, work areas and required deliverables.'},solutions:['scanning']},
 {title:{ar:'التحقق من نقاط التنفيذ',en:'Verifying construction points'},body:{ar:'لقراءة النقاط والمناسيب ومقارنتها بمتطلبات المشروع. يجري اختيار طريقة القياس وفق الدقة وبيئة العمل وشبكة التحكم.',en:'Measure points and levels against project requirements. Select the method based on accuracy, site conditions and control network.'},solutions:['total-station','gnss']},
 {title:{ar:'فهم الموقع قبل التصميم',en:'Understanding the site before design'},body:{ar:'لجمع بيانات السطح واستكشاف الخدمات تحت الأرض. ناقش GPR بحسب التربة والهدف، والمسح الجوي بحسب المساحة والمخرجات.',en:'Collect surface data and investigate underground utilities. Assess GPR for soil and target conditions, and aerial mapping for area and deliverables.'},solutions:['gpr','drone']}
 ],questions:[{ar:'ما القرار أو التقرير المطلوب دعمه بالبيانات؟',en:'Which decision or report must the data support?'},{ar:'ما مستوى التفاصيل والدقة المطلوبة؟',en:'What detail and accuracy are required?'},{ar:'ما صيغة تسليم البيانات لفريق التصميم؟',en:'What data format does the design team need?'}]},
 {slug:'infrastructure',title:{ar:'البنية التحتية والطرق',en:'Infrastructure & roads'},image:'industry-infrastructure-gpr',intro:{ar:'من مسارات الطرق وشبكات الخدمات إلى أعمال التربة وتوثيق المواقع الممتدة. اربط كل مرحلة بالتقنية الأنسب لها.',en:'From road corridors and utility networks to earthworks and long-site documentation. Connect each stage to suitable technology.'},needs:[
 {title:{ar:'رفع المسارات وتوقيعها',en:'Surveying and setting out corridors'},body:{ar:'لتجميع بيانات المسارات وتحديد نقاط التنفيذ. ناقش تغطية التصحيحات والعوائق وشبكة التحكم قبل تحديد تجهيز GNSS أو التوتال ستيشن.',en:'Collect corridor data and set out construction points. Assess correction coverage, obstructions and control before choosing GNSS or total-station equipment.'},solutions:['gnss','total-station']},
 {title:{ar:'استكشاف الخدمات قبل الحفر',en:'Investigating utilities before excavation'},body:{ar:'لتقييم مواقع الأهداف تحت الأرض باستخدام GPR. تتأثر النتائج بنوع التربة والعمق وطبيعة الهدف وتحتاج إلى تفسير متخصص.',en:'Assess underground targets using GPR. Results depend on soil, depth and target type and require specialist interpretation.'},solutions:['gpr']},
 {title:{ar:'أعمال التربة ومتابعة الموقع',en:'Earthworks and site progress'},body:{ar:'قيّم التحكم في المعدات لأعمال التربة، والمسح الجوي لتوثيق المواقع الممتدة. تحدد ملاءمة كل حل وفق المعدات وظروف الموقع والمخرجات.',en:'Assess machine control for earthworks and aerial mapping for extended-site documentation. Suitability depends on equipment, site conditions and deliverables.'},solutions:['machine-control','drone']}
 ],questions:[{ar:'ما طول المسار وطبيعة العوائق بالموقع؟',en:'What is the corridor length and what obstructions exist?'},{ar:'هل العمل يشمل خدمات مدفونة أو أعمال تربة؟',en:'Does the work include buried utilities or earthworks?'},{ar:'ما المعدات وفرق التشغيل المتاحة؟',en:'What machines and operating teams are available?'}]}
];
