import type { Metadata } from 'next';

export type Locale = 'ar' | 'en';
export type Copy = { ar: string; en: string };
export const text = (locale: Locale, value: Copy) => value[locale];
export const SITE = 'https://www.surveyingexperts-sa.com';
export const STORE = 'https://store.surveyingexperts-sa.com';
export const PHONE = '+966540646245';
export const EMAIL = 'Sales@surveyingexperts-sa.com';
export const pathFor = (locale: Locale, path = '') => `${locale === 'ar' ? '/ar' : ''}${path}` || '/en';
export const enquiry = (locale: Locale, values: Record<string,string> = {}) => `${pathFor(locale, '/contact')}?${new URLSearchParams(values)}`;
export const profile = (locale: Locale) => `https://drive.google.com/file/d/${locale === 'ar' ? '1pw2rTyozJbSaSbt8_G28zD81Qzdag7_a' : '1Bgu4lldhOTQgDpDXV2MpO2--AG5OEvOK'}/view`;
export const whatsapp = (message: string) => `https://wa.me/966540646245?text=${encodeURIComponent(message)}`;
export const branches: Copy[] = [{ar:'الرياض',en:'Riyadh'},{ar:'جدة',en:'Jeddah'},{ar:'الدمام',en:'Dammam'},{ar:'تبوك',en:'Tabuk'},{ar:'خميس مشيط',en:'Khamis Mushait'}];
export const brandNames = ['eSurvey', 'Survey Master', 'OmniSLAM', 'Radarteam'];

export type Solution = {
 slug: string; title: Copy; short: Copy; intro: Copy; image: string; imageAlt: Copy;
 uses: Copy[]; questions: Copy[]; kit: Copy[]; models: Copy[]; storePath: string;
 industries: string[]; advanced?: boolean;
};
export const industries = [
 {id:'all',ar:'كل التطبيقات',en:'All applications'},
 {id:'construction',ar:'البناء والتشييد',en:'Construction'},
 {id:'surveying',ar:'مكاتب المساحة',en:'Surveying offices'},
 {id:'infrastructure',ar:'الطرق والبنية التحتية',en:'Roads & infrastructure'},
 {id:'specialist',ar:'المشاريع المتخصصة',en:'Specialist projects'},
];
export const solutions: Solution[] = [
 {slug:'gnss',title:{ar:'أنظمة GNSS وRTK',en:'GNSS & RTK systems'},short:{ar:'للرفع المساحي وتوقيع النقاط وأعمال المواقع المفتوحة.',en:'Positioning, topographic surveys and setting out in the field.'},intro:{ar:'ابدأ بطبيعة الموقع وطريقة العمل. نساعدك في اختيار جهاز الاستقبال ووحدة التحكم وطريقة التصحيح التي تناسب فريقك، مع الإعداد والتدريب العملي.',en:'Start with your site and workflow. We help match a receiver, controller and correction method to your team, with setup and practical guidance.'},image:'gnss-ertk25.jpg',imageAlt:{ar:'جهاز استقبال eSurvey eRTK25',en:'eSurvey eRTK25 receiver'},uses:[{ar:'الرفع الطبوغرافي',en:'Topographic surveys'},{ar:'توقيع النقاط والمحاور',en:'Setting out points and alignments'},{ar:'أعمال الطرق والمواقع',en:'Road and site work'}],questions:[{ar:'هل تعمل بقاعدة وروفر أم بتصحيحات الشبكة؟',en:'Will you use a base and rover or network corrections?'},{ar:'ما طبيعة العوائق والتغطية في الموقع؟',en:'What obstructions and connectivity does the site have?'},{ar:'ما متطلبات الدقة والمخرجات في مشروعك؟',en:'What accuracy and deliverables does your project require?'}],kit:[{ar:'جهاز استقبال وإعداد التصحيحات',en:'Receiver and correction setup'},{ar:'وحدة تحكم وبرنامج ميداني مناسب',en:'Compatible controller and field software'},{ar:'الإكسسوارات والتدريب على التشغيل',en:'Accessories and operating guidance'}],models:[{ar:'eRTK25: ناقش معنا احتياجك لروفر ميداني',en:'eRTK25: discuss your field rover requirements'},{ar:'E800 Pro: ناقش إعداد القاعدة والروفر',en:'E800 Pro: discuss a base and rover configuration'}],storePath:'/collections/e-survey',industries:['construction','surveying','infrastructure']},
 {slug:'total-station',title:{ar:'التوتال ستيشن والميزان',en:'Total stations & levels'},short:{ar:'لقياس الزوايا والمسافات وضبط المناسيب والمحاور.',en:'Angles, distances, levels and precise site layout.'},intro:{ar:'اختيار الجهاز يبدأ من متطلبات القياس وطبيعة الموقع. نساعدك في تجهيز فريقك بالتوتال ستيشن أو الميزان وملحقاتهما، مع التدريب والصيانة والمعايرة.',en:'Choose around the measurement task and site conditions. Equip your team with a total station or level, suitable accessories, training and service support.'},image:'industry-surveying-total-station.png',imageAlt:{ar:'تطبيقات التوتال ستيشن في الموقع',en:'Total station application in the field'},uses:[{ar:'توقيع المحاور',en:'Setting out axes'},{ar:'ضبط المناسيب',en:'Elevation control'},{ar:'التحقق من الأعمال المنفذة',en:'As-built verification'}],questions:[{ar:'ما حدود الدقة المطلوبة؟',en:'What accuracy does the project specify?'},{ar:'هل تحتاج نقل البيانات لبرنامج معين؟',en:'Which software must receive your field data?'},{ar:'ما عدد الأجهزة وخطة المعايرة؟',en:'How many instruments and what calibration schedule?'}],kit:[{ar:'الجهاز المناسب للتطبيق',en:'Instrument matched to the application'},{ar:'حامل وإكسسوارات قياس متوافقة',en:'Tripod and compatible measuring accessories'},{ar:'إرشاد التشغيل وخطة المعايرة',en:'Operating guidance and calibration planning'}],models:[{ar:'أجهزة Survey Master للتوتال ستيشن',en:'Survey Master total stations'},{ar:'موازين وإكسسوارات ضبط المناسيب',en:'Levels and elevation-control accessories'}],storePath:'/collections/survey-master',industries:['construction','surveying','infrastructure']},
 {slug:'scanning',title:{ar:'المسح ثلاثي الأبعاد',en:'3D scanning & LiDAR'},short:{ar:'حوّل تفاصيل الموقع إلى بيانات ثلاثية الأبعاد قابلة للاستخدام.',en:'Capture site detail as usable three-dimensional data.'},intro:{ar:'من توثيق المباني إلى البيئات المعقدة، نساعدك في تقييم سير عمل المسح المناسب. نبدأ بالمخرج المطلوب، ثم الجهاز والبرنامج وطريقة التحقق.',en:'From building documentation to complex environments, choose a capture workflow around the required deliverable, software and verification method.'},image:'scanner-detail.webp',imageAlt:{ar:'جهاز OmniSLAM R8+ للمسح ثلاثي الأبعاد',en:'OmniSLAM R8+ 3D scanner'},uses:[{ar:'توثيق الوضع القائم',en:'Existing-condition documentation'},{ar:'سحب نقطية للمباني والمواقع',en:'Building and site point clouds'},{ar:'دعم سير عمل BIM',en:'Supporting BIM workflows'}],questions:[{ar:'ما المخرج والبرنامج المطلوبان؟',en:'What deliverable and software are required?'},{ar:'هل البيئة داخلية أم خارجية؟',en:'Is the environment indoors or outdoors?'},{ar:'كيف ستتحقق من دقة البيانات؟',en:'How will you verify data accuracy?'}],kit:[{ar:'نظام مسح مناسب لطبيعة الموقع',en:'Scanner suited to the environment'},{ar:'برنامج معالجة وتصدير البيانات',en:'Processing and export software'},{ar:'تجربة عملية وإرشاد سير العمل',en:'Demonstration and workflow guidance'}],models:[{ar:'حلول OmniSLAM للمسح المتحرك',en:'OmniSLAM mobile scanning solutions'},{ar:'ناقش خيارات المسح الثابت والمتحرك',en:'Discuss static and mobile capture options'}],storePath:'/collections/omnislam',industries:['construction','surveying','specialist'],advanced:true},
 {slug:'machine-control',title:{ar:'التحكم في المعدات',en:'Machine control'},short:{ar:'دعم أعمال التسوية والتنفيذ ببيانات التصميم والتوجيه.',en:'Support grading and execution with design data and guidance.'},intro:{ar:'نراجع نوع المعدة وطبيعة العمل وملفات التصميم لتحديد إمكانية تطبيق نظام التحكم المناسب. التوافق والتجهيز العملي جزء أساسي من التقييم.',en:'Review the machine, task and design files to assess a suitable guidance setup. Compatibility and practical installation are central to the evaluation.'},image:'machine-control-kit.webp',imageAlt:{ar:'نظام eSurvey eME30 للتحكم في الحفارات: وحدة التحكم والمستقبلات والحساسات',en:'eSurvey eME30 excavator control system with controller, receivers and sensors'},uses:[{ar:'أعمال التسوية',en:'Grading operations'},{ar:'تنفيذ أعمال الطرق',en:'Road construction'},{ar:'الربط مع بيانات التصميم',en:'Working with design data'}],questions:[{ar:'ما نوع وموديل المعدة؟',en:'What is the machine make and model?'},{ar:'ما طبيعة أعمال التنفيذ؟',en:'What operations will the machine perform?'},{ar:'هل ملفات التصميم جاهزة؟',en:'Are suitable design files available?'}],kit:[{ar:'تقييم توافق المعدة',en:'Machine compatibility assessment'},{ar:'تحديد نظام التوجيه المناسب',en:'Guidance-system selection'},{ar:'تنسيق التجهيز والتدريب',en:'Installation and training coordination'}],models:[{ar:'توصية حسب نوع المعدة والتطبيق',en:'Application- and machine-specific recommendation'}],storePath:'/collections/all',industries:['construction','infrastructure']},
 {slug:'gpr',title:{ar:'كشف ما تحت الأرض',en:'Underground detection'},short:{ar:'افهم ظروف الموقع قبل الحفر باستخدام تقنيات الكشف المناسبة.',en:'Understand subsurface conditions before excavation.'},intro:{ar:'تختلف نتيجة الكشف باختلاف الهدف والتربة وبيئة الموقع. نساعدك في تقييم تقنية GPR أو أدوات تحديد المرافق وفق المهمة، مع تجربة وإرشاد عند الحاجة.',en:'Detection depends on the target, soil and site conditions. Assess GPR or utility-location tools around the investigation, with demonstration and guidance when needed.'},image:'advanced-gpr-detection.png',imageAlt:{ar:'تطبيق لكشف ما تحت الأرض',en:'Underground detection application'},uses:[{ar:'التحقيق قبل الحفر',en:'Pre-excavation investigation'},{ar:'تحديد مسارات المرافق',en:'Utility route investigation'},{ar:'توثيق بيانات باطن الأرض',en:'Subsurface data documentation'}],questions:[{ar:'ما الهدف المطلوب كشفه؟',en:'What are you trying to detect?'},{ar:'ما طبيعة التربة والموقع؟',en:'What are the ground and site conditions?'},{ar:'هل تحتاج تجربة ميدانية قبل الاختيار؟',en:'Would a field demonstration support selection?'}],kit:[{ar:'أداة كشف تناسب المهمة',en:'Detection tool suited to the task'},{ar:'برنامج وإكسسوارات مناسبة',en:'Suitable software and accessories'},{ar:'إرشاد التشغيل وفهم المخرجات',en:'Operating and output-interpretation guidance'}],models:[{ar:'حلول Radarteam للكشف الأرضي',en:'Radarteam ground-penetrating radar solutions'}],storePath:'/collections/radarteam',industries:['infrastructure','specialist','surveying'],advanced:true},
 {slug:'marine',title:{ar:'المسح البحري',en:'Marine surveying'},short:{ar:'حلول قياس الأعماق وتحديد المواقع للمشاريع المائية.',en:'Depth measurement and positioning for water-based projects.'},intro:{ar:'ابدأ ببيئة المياه ونطاق المشروع ونوع البيانات المطلوبة. نساعدك في مناقشة تجهيزات قياس الأعماق وتحديد المواقع وسير عمل جمع البيانات.',en:'Start with the water environment, project scale and data requirements. Discuss depth measurement, positioning equipment and the data-collection workflow.'},image:'advanced-marine-surveying.png',imageAlt:{ar:'تطبيق للمسح في بيئة مائية',en:'Surveying application in a water environment'},uses:[{ar:'قياس الأعماق',en:'Bathymetric measurement'},{ar:'تحديد المواقع البحرية',en:'Marine positioning'},{ar:'توثيق المشاريع الساحلية والمائية',en:'Coastal and water-project documentation'}],questions:[{ar:'ما نوع وامتداد المسطح المائي؟',en:'What type and extent of water body?'},{ar:'ما متطلبات الأعماق والمخرجات؟',en:'What depth and output requirements apply?'},{ar:'ما تجهيزات المنصة المتاحة؟',en:'What survey platform is available?'}],kit:[{ar:'تجهيزات قياس الأعماق',en:'Depth-measurement equipment'},{ar:'نظام تحديد مواقع متوافق',en:'Compatible positioning system'},{ar:'إرشاد جمع البيانات',en:'Data-collection guidance'}],models:[{ar:'حلول Survey Master للمسح البحري',en:'Survey Master marine surveying solutions'}],storePath:'/collections/survey-master',industries:['specialist','surveying'],advanced:true},
 {slug:'drone',title:{ar:'المسح الجوي والدرون',en:'Drone & aerial mapping'},short:{ar:'لجمع بيانات المواقع الواسعة والتوثيق من الجو.',en:'Capture large sites and document projects from the air.'},intro:{ar:'نجهّزك بحلول المسح الجوي والدرون حسب مساحة الموقع والمخرجات المطلوبة، من اختيار المنصة والحمولة المناسبة إلى برامج المعالجة والتدريب والدعم.',en:'Equip your team with drone and aerial-mapping solutions matched to your site and deliverables, from platform and payload selection to processing software, training and support.'},image:'advanced-drone-mapping.jpg',imageAlt:{ar:'درون لتطبيقات المسح الجوي',en:'Drone for aerial surveying applications'},uses:[{ar:'خرائط المواقع',en:'Site mapping'},{ar:'توثيق تقدم الأعمال',en:'Progress documentation'},{ar:'جمع البيانات الجوية',en:'Aerial data collection'}],questions:[{ar:'ما المخرج المطلوب ومساحة الموقع؟',en:'What deliverable and site extent?'},{ar:'هل تحتاج تصويرًا أم LiDAR؟',en:'Do you need imagery or LiDAR?'},{ar:'ما ترتيبات التشغيل والتصاريح اللازمة؟',en:'What operating arrangements and permissions are needed?'}],kit:[{ar:'منصة وحمولة مناسبة للمهمة',en:'Task-appropriate platform and payload'},{ar:'برنامج معالجة البيانات',en:'Data-processing software'},{ar:'تقييم سير العمل والتدريب',en:'Workflow assessment and training'}],models:[{ar:'خيارات DJI وQuantum Systems حلول المسح الجوي',en:'DJI and Quantum Systems options for aerial surveying'}],storePath:'/search?q=drone',industries:['infrastructure','surveying','specialist'],advanced:true},
];

export function pageMeta(locale: Locale, title: string, description: string, path = ''): Metadata {
 return {title,description,alternates:{canonical:SITE+pathFor(locale,path),languages:{en:SITE+pathFor('en',path),ar:SITE+pathFor('ar',path),'x-default':SITE+pathFor('ar',path)}},openGraph:{title,description,url:SITE+pathFor(locale,path),locale:locale==='ar'?'ar_SA':'en_US',alternateLocale:locale==='ar'?'en_US':'ar_SA',siteName:locale==='ar'?'خبراء المساحة':'Surveying Experts',type:'website',images:[{url:SITE+'/images/photos/gnss-ertk25.jpg',width:1920,height:1280,alt:'Surveying Experts: eSurvey eRTK25'}]},twitter:{card:'summary_large_image',title,description,images:[SITE+'/images/photos/gnss-ertk25.jpg']}};
}
