import {FloatingWhatsApp} from './FloatingWhatsApp';
import Link from 'next/link';
import Image from 'next/image';
import localFont from 'next/font/local';
import {ArrowUpRight, Phone, Mail} from 'lucide-react';
import {Navigation} from './Navigation';
import {Locale, pathFor, STORE, PHONE, EMAIL, profile} from '@/lib/site';
import '@/app/globals.css';

const arabic=localFont({src:[{path:'../../public/fonts/thmanyah/thmanyahsans-Regular.woff2',weight:'400'},{path:'../../public/fonts/thmanyah/thmanyahsans-Medium.woff2',weight:'500'},{path:'../../public/fonts/thmanyah/thmanyahsans-Bold.woff2',weight:'700'}],variable:'--font-arabic',display:'swap',preload:true});
const english=localFont({src:[{path:'../../public/fonts/ibm-plex/IBMPlexSans-Regular.ttf',weight:'400'},{path:'../../public/fonts/ibm-plex/IBMPlexSans-Medium.ttf',weight:'500'},{path:'../../public/fonts/ibm-plex/IBMPlexSans-Bold.ttf',weight:'700'}],variable:'--font-english',display:'swap',preload:true});
export function Document({locale,children}:{locale:Locale;children:React.ReactNode}){
 const ar=locale==='ar';
 return <html lang={locale} dir={ar?'rtl':'ltr'} className={`${arabic.variable} ${english.variable}`}><body><Navigation locale={locale}/><main id="main" tabIndex={-1}>{children}</main><footer className="site-footer"><div className="wrap footer-grid"><div className="footer-brand"><Image className="footer-logo" src="/images/logo-on-dark.png" alt={ar?'خبراء المساحة':'Surveying Experts'} width={250} height={90}/><p>{ar?'المعدات المناسبة. والدعم الحقيقي الذي يساندك في الميدان.':'The right equipment. Real support by your side in the field.'}</p><a href={`tel:${PHONE}`}><Phone size={16}/><bdi>+966 54 064 6245</bdi></a><a href={`mailto:${EMAIL}`}><Mail size={16}/><bdi>{EMAIL}</bdi></a></div><div><h3>{ar?'ابدأ من هنا':'Find your way'}</h3>{[['/solutions',ar?'الحلول والأجهزة':'Solutions & equipment'],['/advanced-solutions',ar?'الحلول المتقدمة':'Advanced solutions'],['/rental',ar?'تأجير الأجهزة':'Equipment rental'],['/maintenance-calibration',ar?'الصيانة والمعايرة':'Maintenance & calibration']].map(([p,l])=><Link href={pathFor(locale,p)} key={p}>{l}</Link>)}</div><div><h3>{ar?'تعرف علينا':'Get to know us'}</h3><Link href={pathFor(locale,'/about')}>{ar?'عن الشركة':'About us'}</Link><Link href={pathFor(locale,'/referral-program')}>{ar?'برنامج رشّح عميلًا':'Refer a Client'}</Link><Link href={pathFor(locale,'/media')}>{ar?'الميديا':'Media'}</Link><Link href={pathFor(locale,'/contact')+'#branches'}>{ar?'الفروع والتواصل':'Branches & contact'}</Link><a href={profile(locale)} target="_blank" rel="noopener noreferrer">{ar?'ملف الشركة':'Company profile'}<ArrowUpRight size={14}/></a></div><div className="footer-store"><span className="eyebrow">{ar?'جاهز للشراء؟':'READY TO BUY?'}</span><h3>{ar?'تصفح متجرنا الإلكتروني':'Explore our online store'}</h3><p>{ar?'الأجهزة والإكسسوارات والتفاصيل التجارية في مكان واحد.':'Equipment, accessories and current commercial details in one place.'}</p><a className="button yellow" href={STORE}>{ar?'زيارة المتجر':'Visit the store'}<ArrowUpRight size={17}/></a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} {ar?'خبراء المساحة. جميع الحقوق محفوظة.':'Surveying Experts. All rights reserved.'}</span><div><Link href={pathFor(locale,'/privacy')}>{ar?'الخصوصية':'Privacy'}</Link><a href="https://www.youtube.com/@surveyingexperts-sa" target="_blank" rel="noopener noreferrer">YouTube</a><a href="https://www.linkedin.com/company/surveyingexperts" target="_blank" rel="noopener noreferrer">LinkedIn</a></div></div></footer><FloatingWhatsApp locale={locale}/></body></html>
}
