'use client';
import {sectors} from '@/lib/sectors';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight, ArrowUpRight, MapPin, Phone, MessageSquare} from 'lucide-react';
import {Locale, solutions, industries, pathFor, text, branches, enquiry, PHONE, whatsapp} from '@/lib/site';

export function SolutionFinder({locale,advanced=false}:{locale:Locale;advanced?:boolean}){
 const [industry,setIndustry]=useState('all');const ar=locale==='ar';
 const items=solutions.filter(s=>(!advanced||s.advanced)&&(industry==='all'||s.industries.includes(industry)));
 return <div id="equipment"><div className="filter-bar" role="group" aria-label={ar?'تصفية حسب التطبيق':'Filter by application'}>{industries.map(i=><button key={i.id} aria-pressed={industry===i.id} onClick={()=>setIndustry(i.id)}>{i[locale]}</button>)}</div><p className="filter-status" role="status">{ar?`${items.length} مجالات تناسب اختيارك`:`${items.length} solution areas for your selection`}</p><div className="solution-grid">{items.map((s)=><Link id={s.slug} key={s.slug} href={pathFor(locale,`/solutions/${s.slug}`)} className="solution-card"><div className="card-image"><Image quality={92} loading={advanced?'eager':undefined} src={`/images/optimized/${s.image.replace(/\.[^.]+$/,'.webp')}`} alt={text(locale,s.imageAlt)} fill sizes="(max-width: 640px) 100vw, (max-width: 1000px) 50vw, 33vw"/></div><div className="card-body"><h3>{text(locale,s.title)}</h3><p>{text(locale,s.short)}</p><span className="text-link">{ar?'اكتشف الحل':'Explore solution'}<ArrowRight className="direction-arrow" size={18}/></span></div></Link>)}</div></div>
}

export function PreviousBranchPicker({locale}:{locale:Locale}){
 const [index,setIndex]=useState(0);const ar=locale==='ar',city=branches[index][locale];
 return <div className="branch-picker" id="branches"><div className="filter-bar" role="group" aria-label={ar?'اختر المدينة':'Choose a city'}>{branches.map((b,i)=><button key={b.en} aria-pressed={index===i} onClick={()=>setIndex(i)}>{b[locale]}</button>)}</div><div className="branch-panel"><div><MapPin size={30}/><h3>{ar?`تواصل مع فريقنا في ${city}`:`Connect with our team in ${city}`}</h3><p>{ar?'نسّق الزيارة أو تجربة الجهاز مع فريقنا، وتأكد من توفر الخدمة المناسبة قبل التوجه للفرع.':'Arrange a visit or equipment demonstration with our team and confirm service availability before travelling.'}</p><a href={`tel:${PHONE}`} className="text-link"><Phone size={17}/><bdi>+966 54 064 6245</bdi><span className="muted">{ar?'التواصل المركزي':'Central contact'}</span></a></div><div className="branch-actions"><Link href={enquiry(locale,{branch:branches[index].en,intent:'consultation'})} className="button navy">{ar?'نسّق زيارتك':'Arrange your visit'}<ArrowRight className="direction-arrow" size={17}/></Link><a className="button outline" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent('Surveying Experts '+branches[index].en+' Saudi Arabia')}`} target="_blank" rel="noopener noreferrer">{ar?'ابحث عن الفرع على الخريطة':'Find the branch on Maps'}<ArrowUpRight size={17}/></a></div></div></div>
}

export {BranchLocations as BranchPicker} from './BranchLocations';
import {maintenancePackages,calibrationServices} from '@/lib/restored-content';
const intents=[['quote','عرض سعر','Equipment quote'],['consultation','اختيار الجهاز المناسب','Equipment recommendation'],['demo','تجربة جهاز','Equipment demonstration'],['service','صيانة أو معايرة جهاز','Device service / calibration'],['fleet','صيانة أسطول أجهزة','Fleet maintenance'],['rental','تأجير أجهزة','Equipment rental'],['training','تدريب ودعم فني','Training & technical support'],['documents','مستندات الشركة','Company documents'],['referral','برنامج رشّح عميلًا','Refer a Client']];
import {EmailSubmission} from './EmailSubmission';
export function EnquiryForm({locale,initial}:{locale:Locale;initial:Record<string,string>}){
 const ar=locale==='ar';
 const selectedSector=sectors.find(s=>s.slug===initial.sector);
 const [intent,setIntent]=useState(intents.some(i=>i[0]===initial.intent)?initial.intent:'quote');
 const [solution,setSolution]=useState(solutions.some(s=>s.slug===initial.solution)?initial.solution:'');
 const [branch,setBranch]=useState(branches.some(b=>b.en===initial.branch)?initial.branch:'');
 const [plan,setPlan]=useState(maintenancePackages.some(p=>p.id===initial.plan)?initial.plan:'');
 const [prepared,setPrepared]=useState('');
 const [copied,setCopied]=useState(false); const previewHeading=useRef<HTMLHeadingElement>(null),formHeading=useRef<HTMLHeadingElement>(null),reviewed=useRef(false); useEffect(()=>{if(!prepared&&!reviewed.current)return; reviewed.current=true;const heading=prepared?previewHeading.current:formHeading.current;heading?.focus({preventScroll:true});heading?.scrollIntoView({block:"start"});},[prepared]);
 function prepare(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const subject=intents.find(i=>i[0]===intent)![ar?1:2];const chosen=solutions.find(s=>s.slug===solution);const lines=[ar?'مرحبًا خبراء المساحة، أود الاستفسار عن:':'Hello Surveying Experts, I would like to enquire about:',subject,intent==='fleet'&&plan?text(locale,maintenancePackages.find(p=>p.id===plan)!.title):'',initial.service?text(locale,calibrationServices.find(s=>s.id===initial.service)?.title||{ar:'',en:''}):'',chosen?text(locale,chosen.title):'',`${ar?'الاسم':'Name'}: ${String(f.get('name')).trim()}`,f.get('company')?`${ar?'الشركة':'Company'}: ${String(f.get('company')).trim()}`:'',`${ar?'رقم التواصل':'Contact number'}: ${String(f.get('phone')).trim()}`,branch?`${ar?'الفرع':'Branch'}: ${branches.find(b=>b.en===branch)?.[locale]}`:'',f.get('device')?`${ar?'الجهاز / عدد الأجهزة':'Device / number of devices'}: ${String(f.get('device')).trim()}`:'',String(f.get('message')||'').trim()].filter(Boolean);setPrepared(lines.join('\n'));setCopied(false);}
 return <div className="enquiry-form">{prepared&&<div className="request-preview" role="status"><MessageSquare size={32}/><h2 ref={previewHeading} tabIndex={-1}>{ar?'طلبك جاهز للمشاركة':'Your enquiry is ready'}</h2><p>{ar?'راجع التفاصيل، ثم أرسل الطلب بالبريد من الموقع أو افتح واتساب لإرساله.':'Review the details, then submit by email here or open WhatsApp to send your enquiry.'}</p><pre>{prepared}</pre><div className="actions"><a className="button yellow" data-action="whatsapp_enquiry" href={whatsapp(prepared)} target="_blank" rel="noopener noreferrer">{ar?'افتح واتساب لإرسال الطلب':'Open WhatsApp to send'}<ArrowUpRight size={18}/></a></div><EmailSubmission key={prepared} locale={locale} message={prepared}/><div className="preview-alternatives"><button className="text-link" onClick={async()=>{try{await navigator.clipboard.writeText(prepared);setCopied(true)}catch{setCopied(false)}}}>{copied?(ar?'تم النسخ':'Copied'):(ar?'انسخ الطلب':'Copy enquiry')}</button><button className="text-link" onClick={()=>setPrepared('')}>{ar?'عدّل الطلب':'Edit enquiry'}</button></div></div>}<form hidden={!!prepared} onSubmit={prepare}>
 <div className="form-heading"><span className="eyebrow">{ar?'لنبدأ باحتياجك':'START WITH YOUR NEED'}</span><h2 ref={formHeading} tabIndex={-1}>{ar?'كيف نساعدك؟':'How can we help?'}</h2><p>{ar?'اكتب تفاصيل طلبك، ثم راجعها واختر إرسالها لفريقنا عبر واتساب أو البريد الإلكتروني.':'Enter your enquiry, then review it and choose WhatsApp or email to contact our team.'}</p></div>
 <div className="form-row"><div><label htmlFor="intent">{ar?'نوع الطلب':'Enquiry type'}</label><select id="intent" name="intent" value={intent} onChange={e=>setIntent(e.target.value)}>{intents.map(i=><option key={i[0]} value={i[0]}>{i[ar?1:2]}</option>)}</select></div><div><label htmlFor="solution">{ar?'مجال الحل':'Solution area'}</label><select id="solution" value={solution} onChange={e=>setSolution(e.target.value)}><option value="">{ar?'ساعدني في الاختيار':'Help me choose'}</option>{solutions.map(s=><option key={s.slug} value={s.slug}>{text(locale,s.title)}</option>)}</select></div></div>
 {intent==='fleet'&&<div><label htmlFor="plan">{ar?'الباقة المطلوبة':'Requested plan'}</label><select id="plan" value={plan} onChange={e=>setPlan(e.target.value)}><option value="">{ar?'ساعدني في اختيار الباقة':'Help me choose a plan'}</option>{maintenancePackages.map(p=><option value={p.id} key={p.id}>{text(locale,p.title)}: {p.price} {ar?'ر.س':'SAR'}</option>)}</select></div>}
 <div className="form-row"><div><label htmlFor="name">{ar?'الاسم *':'Name *'}</label><input id="name" name="name" autoComplete="name" required maxLength={100}/></div><div><label htmlFor="phone">{ar?'رقم الهاتف / الواتساب *':'Phone / WhatsApp *'}</label><input id="phone" name="phone" type="tel" dir="ltr" inputMode="tel" autoComplete="tel" placeholder="+966 …" required minLength={7} maxLength={24} pattern="[+0-9٠-٩۰-۹ \(\)\-]{7,24}"/></div></div>
 <div className="form-row"><div><label htmlFor="company">{ar?'الشركة (اختياري)':'Company (optional)'}</label><input id="company" name="company" autoComplete="organization" maxLength={120}/></div><div><label htmlFor="branch">{ar?'الفرع المفضل':'Preferred branch'}</label><select id="branch" value={branch} onChange={e=>setBranch(e.target.value)}><option value="">{ar?'دون تفضيل':'No preference'}</option>{branches.map(b=><option key={b.en} value={b.en}>{b[locale]}</option>)}</select></div></div>
 {['service','fleet','rental','training'].includes(intent)&&<div><label htmlFor="device">{ar?'نوع الجهاز وموديله أو عدد الأجهزة':'Instrument model or number of devices'}</label><input id="device" name="device" maxLength={180}/></div>}
 <div><label htmlFor="message">{ar?'عن مشروعك أو طلبك':'About your project or request'}</label><textarea id="message" name="message" defaultValue={selectedSector?`${ar?'قطاع المشروع':'Project sector'}: ${text(locale,selectedSector.title)}\n`:undefined} rows={4} maxLength={1200} placeholder={ar?'طبيعة العمل، نوع الجهاز أو الخدمة المطلوبة…':'Your field task, equipment or service requirements…'}/></div>
 <p className="form-note">{ar?'الحقول بعلامة * مطلوبة. ستراجع طلبك وتختار طريقة إرساله في الخطوة التالية.':'Fields marked * are required. Review your enquiry and choose how to send it in the next step.'} <Link href={pathFor(locale,'/privacy')}>{ar?'الخصوصية':'Privacy'}</Link></p>
 <button className="button yellow" type="submit">{ar?'راجع الطلب واختر طريقة الإرسال':'Review enquiry & choose how to send'}<ArrowRight className="direction-arrow" size={18}/></button>
 </form></div>
}
