import {ArrowUpRight,Youtube,Facebook,Instagram,Linkedin,Music2,Globe} from 'lucide-react';
import {Locale,STORE} from '@/lib/site';
import {MediaGallery} from './MediaGallery';
const socials=[
 {name:'YouTube',handle:'@surveyingexperts-sa',href:'https://www.youtube.com/@surveyingexperts-sa',icon:Youtube},
 {name:'Instagram',handle:'@surveyingexperts_sa',href:'https://www.instagram.com/surveyingexperts_sa',icon:Instagram},
 {name:'Facebook',handle:'SurveyingExp1',href:'https://www.facebook.com/SurveyingExp1',icon:Facebook},
 {name:'LinkedIn',handle:'Surveying Experts',href:'https://www.linkedin.com/company/surveyingexperts',icon:Linkedin},
 {name:'TikTok',handle:'@surveying.experts',href:'https://www.tiktok.com/@surveying.experts',icon:Music2},
];
export function MediaPage({locale}:{locale:Locale}){const ar=locale==='ar';return <div className="media-page"><section className="media-opening"><div className="wrap"><span className="eyebrow">{ar?'ميديا خبراء المساحة':'SURVEYING EXPERTS MEDIA'}</span><h1>{ar?'من قلب الميدان.\nعلى شاشتك.':'From the field.\nTo your screen.'}</h1><div className="media-opening-bottom"><p>{ar?'تجارب أجهزة، لقاءات، وكواليس من عالم خبراء المساحة. شغّل الفيديو وخليك معنا.':'Equipment in action, conversations and a closer look at Surveying Experts. Press play and join us.'}</p><a className="button yellow" href="#our-channels">{ar?'تابعنا على منصتك':'Find your platform'}<ArrowUpRight size={18}/></a></div></div></section><section className="section"><div className="wrap"><div className="section-heading-row"><div><span className="eyebrow">{ar?'من قناتنا على يوتيوب':'FROM OUR YOUTUBE CHANNEL'}</span><h2>{ar?'اضغط تشغيل.':'Press play.'}</h2></div><a className="text-link" href="https://www.youtube.com/@surveyingexperts-sa/videos" target="_blank" rel="noopener noreferrer">{ar?'كل الفيديوهات':'All videos'}<ArrowUpRight size={18}/></a></div><MediaGallery locale={locale}/></div></section><section className="section media-socials" id="our-channels"><div className="wrap"><span className="eyebrow">{ar?'خلّينا على تواصل':'STAY CONNECTED'}</span><h2>{ar?'تلاقينا هنا.':'Find us here.'}</h2><div className="media-social-grid">{socials.map(({name,handle,href,icon:Icon})=><a key={name} href={href} target="_blank" rel="noopener noreferrer"><Icon size={28}/><div><h3>{name}</h3><span dir="ltr">{handle}</span></div><ArrowUpRight size={21}/></a>)}</div><a className="media-store-link" href={STORE} target="_blank" rel="noopener noreferrer"><Globe size={22}/>{ar?'ومتجرنا لكل تجهيزاتك':'And our store for your equipment'}<ArrowUpRight size={18}/></a></div></section></div>}
